//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAuthorization.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTicket
    {
        public int EVT_ID { get; set; }
        public int EV_ID { get; set; }
        public int CL_ID { get; set; }
        public System.DateTime EVT_Date { get; set; }
        public int PM_ID { get; set; }
        public int EVT_CostTicket { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Event Event { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
