//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAuthorization.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventTicket = new HashSet<EventTicket>();
        }
    
        public int EV_ID { get; set; }
        public string EV_Name { get; set; }
        public string EV_Description { get; set; }
        public System.DateTime EV_DateEvent { get; set; }
        public int EV_CostEvent { get; set; }
        public int EV_QuantitySeats { get; set; }
        public int H_ID { get; set; }
    
        public virtual Hall Hall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTicket> EventTicket { get; set; }
    }
}
