//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAuthorization.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int O_ID { get; set; }
        public int CL_ID { get; set; }
        public int TO_ID { get; set; }
        public string O_Name { get; set; }
        public string O_Description { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TypeOrder TypeOrder { get; set; }
    }
}
