//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAuthorization.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int STAFF_ID { get; set; }
        public string STAFF_LastName { get; set; }
        public string STAFF_FirstName { get; set; }
        public string STAFF_Patronymic { get; set; }
        public string STAFF_Phone { get; set; }
        public string STAFF_Email { get; set; }
        public string STAFF_Password { get; set; }
        public System.DateTime STAFF_DateOfBirth { get; set; }
        public int R_ID { get; set; }
        public Nullable<int> STAFF_Experience { get; set; }
        public int STAFF_Salary { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
